# Done to increase the memory available to gradle.
	org.gradle.jvmargs = -Xmx1G

# Minecraft Properties
	minecraft_version = 1.21.5
	wider_minecraft_version = 1.21.5

# Fabric Properties
	# check these on https://fabricmc.net/develop/
	yarn_mappings = 1
	tiny_version = 2
	loader_version = 0.16.13
	loom_version = 1.10-SNAPSHOT

# Mod Properties
	mod_version = 1.12.0
	maven_group = com.shnupbups
	mod_name = redstone-bits
	version_meta = fabric

# Mod Publish Plugin
	mod_publish_plugin_version = 0.8.4
	modrinth_project = 4RK1aHVB
	cf_project = 321014

# Dependencies
	# check on https://fabricmc.net/develop/
	fapi_version = 0.121.0+1.21.5

	# check on linkie at https://linkie.shedaniel.dev/dependencies?loader=fabric#dep-2
	# or on maven at https://maven.shedaniel.me/me/shedaniel/cloth/cloth-config-fabric/
	cloth_config_version = 18.0.145

# Dev Environment Stuff
	# check on linkie at https://linkie.shedaniel.dev/dependencies?loader=fabric#dep-2
	# or on maven at https://maven.shedaniel.me/me/shedaniel/RoughlyEnoughItems-fabric/
	rei_version = 19.0.806

	# check on linkie at https://linkie.shedaniel.dev/dependencies?loader=fabric#dep-1
	# or on maven at https://maven.shedaniel.me/dev/architectury/architectury-fabric/
	arch_version = 16.1.4

	# check on linkie at https://linkie.shedaniel.dev/dependencies?loader=fabric#dep-3
	# or on maven at https://maven.terraformersmc.com/releases/com/terraformersmc/modmenu
	modmenu_version = 14.0.0-rc.2